version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

#   redis:
#     image: redis:7
#     container_name: redis_app
#     command: --port 5370
#     expose:
#       - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    depends_on:
      - db
    #   - redis

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env-non-dev
    ports:
      - "5050:80"

#   celery:
#     build:
#       context: .
#     env_file:
#       - .env-non-dev
#     container_name: celery_app
#     command: ["/fastapi_app/docker/celery.sh", "celery"]
#     depends_on:
#       - redis

#   flower:
#     build:
#       context: .
#     env_file:
#       - .env-non-dev
#     container_name: flower_app
#     command: ["/fastapi_app/docker/celery.sh", "flower"]
#     depends_on:
#       - redis
#       - celery
#     ports:
#       - 8888:5555